run:
    name: A2C
    max_steps_episode: 500
    n_episodes: 1000
    n_eval_timesteps: 10**6
    n_eval_episodes: 100

nn:
    input_dim: 4
    output_dim: 2
    features: [256, 256]
    lr: 0.001
    optim: AdamW
    loss: "MSE"

agent:
    gamma: 0.99
    n_steps: 50
