run:
  name: base
  max_steps: 500_000
  n_episodes: 500
  evaluation_interval: 10
  n_eval_episodes: 20

nn:
  policy_network:
    input_dim: 4
    output_dim: 2
    features: [256, 256]
    lr: 5.e-4
    optim: AdamW

  value_network:
    input_dim: 4
    output_dim: 1
    features: [256, 256]
    lr: 1.e-4
    optim: Adam

agent:
  gamma: 0.99

