run:
  name: cartpole-baseline
  max_steps: 500_000

nn:
  input_dim: 4
  output_dim: 2
  features: [64, 128, 64]
  lr: 3e-4
  loss: SmoothL1
  optim: AdamW

agent:
  policy: egreedy
  epsilon: 0.1
  gamma: 0.99
